{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-prepper.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "kube-system"}}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
